### ISSUE TITLE
Question of Fig.4 in paper

### ISSUE THREAD

**Issue by jieeeeeeeeeee** [cvg/pixel-perfect-sfm#62]
This is exciting work. How was the correlation map in Figure 4 calculated?

![image](https://user-images.githubusercontent.com/31924229/174212675-d0808dfb-f04a-467e-8016-8e4936015696.png)

Was it computed using normalized cross-correlation (NCC)? If so, here's a question: Deep features may be 128-dimensional, while the reference image is a 1-dimensional greyscale map. How did they compute the correlation map?

**Comment by Skydes** [comment]
Here we visualize the pixel-wise correlation between each feature and the reference feature of the track, as defined in the featuremetric bundle adjustment (feature closest to the robust mean). IIRC the references are in the top row because their correlation maps are much cleaner than the others. We do not compute the correlation with intensity images, only with deep features.

**Comment by jieeeeeeeeeee** [comment]
Got it! Thanks a lot. :)
One more question, sparse correspondence based on deep features is compelling. Do you think it is feasible to do dense correspondence and reconstruction using deep features?

**Comment by Skydes** [comment]
Both hloc and PixSfM actually support reconstruction with LoFTR (semi-dense matching). This is not yet merged into the main branches:
https://github.com/cvg/Hierarchical-Localization/pull/173
https://github.com/cvg/pixel-perfect-sfm/tree/semi-dense-matching
